# Generated by Django 5.0.3 on 2024-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
